config/routes.rb
Taskman::Application.routes.draw do
  resources :sprints

  resources :tasks

 root :to => "tasks#index"

end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :sprints
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  # GET /sprints
  # GET /sprints.xml
  def index
    @sprints = Sprint.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sprints }
    end
  end

  # GET /sprints/1
  # GET /sprints/1.xml
  def show
    @sprint = Sprint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sprint }
    end
  end

  # GET /sprints/new
  # GET /sprints/new.xml
  def new
    @sprint = Sprint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sprint }
    end
  end

  # GET /sprints/1/edit
  def edit
    @sprint = Sprint.find(params[:id])
  end

  # POST /sprints
  # POST /sprints.xml
  def create
    @sprint = Sprint.new(params[:sprint])

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to(@sprint, :notice => 'Sprint was successfully created.') }
        format.xml  { render :xml => @sprint, :status => :created, :location => @sprint }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sprint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sprints/1
  # PUT /sprints/1.xml
  def update
    @sprint = Sprint.find(params[:id])

    respond_to do |format|
      if @sprint.update_attributes(params[:sprint])
        format.html { redirect_to(@sprint, :notice => 'Sprint was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sprint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.xml
  def destroy
    @sprint = Sprint.find(params[:id])
    @sprint.destroy

    respond_to do |format|
      format.html { redirect_to(sprints_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(@task, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskman</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sprints/_form.html.erb
<%= form_for(@sprint) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :stop %><br />
    <%= f.datetime_select :stop %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.text_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :log %><br />
    <%= f.text_area :log %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sprints/edit.html.erb
<h1>Editing sprint</h1>

<%= render 'form' %>

<%= link_to 'Show', @sprint %> |
<%= link_to 'Back', sprints_path %>

app/views/sprints/index.html.erb
<h1>Listing sprints</h1>

<table>
  <tr>
    <th>Start</th>
    <th>Stop</th>
    <th>Task</th>
    <th>Log</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sprints.each do |sprint| %>
  <tr>
    <td><%= sprint.start %></td>
    <td><%= sprint.stop %></td>
    <td><%= sprint.task_id %></td>
    <td><%= sprint.log %></td>
    <td><%= link_to 'Show', sprint %></td>
    <td><%= link_to 'Edit', edit_sprint_path(sprint) %></td>
    <td><%= link_to 'Destroy', sprint, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sprint', new_sprint_path %>

app/views/sprints/new.html.erb
<h1>New sprint</h1>

<%= render 'form' %>

<%= link_to 'Back', sprints_path %>

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start:</b>
  <%= @sprint.start %>
</p>

<p>
  <b>Stop:</b>
  <%= @sprint.stop %>
</p>

<p>
  <b>Task:</b>
  <%= @sprint.task_id %>
</p>

<p>
  <b>Log:</b>
  <%= @sprint.log %>
</p>


<%= link_to 'Edit', edit_sprint_path(@sprint) %> |
<%= link_to 'Back', sprints_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
<P> Below contains the history of tasks</p>
<table border="1"1>
  <tr>
    <th>Name</th>
    <th>Date Stamp</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.created_at.strftime("%A %B %d, %Y %H:%M") %></td>
    <td><%= task.description %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Sprints</b>
  <% @task.sprints.each do |sprint| %>
    Start: <%= sprint.start %><br/>
    Stop: <%= sprint.stop %><br />
    Log: <%= sprint.log %><br />
    <hr>
  <% end %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>